import Head from 'next/head'

import NavMenu from 'components/nav-menu'
import Logo from 'components/logo'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-1/2 bg-gradient-to-t from-indigo-200 to-white lg:h-screen">
        <nav className="fixed top-0 w-full bg-white">
          <div className="container mx-auto flex justify-between p-5">
            <Logo />

            <NavMenu className="hidden items-center gap-x-8 text-sm font-bold uppercase text-gray-600 md:flex" />
          </div>
        </nav>
        <div className="mt-20 bg-blue-300">Whereas recognition</div>
      </div>
    </>
  )
}
