import Head from 'next/head'
import Image from 'next/image'

import LogoImage from 'images/logo.png'

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-1/2 bg-gradient-to-t from-indigo-200 to-white lg:h-screen">
        <nav className="fixed top-0 w-full bg-white">
          <div className="container mx-auto flex justify-between py-5">
            <div className="flex items-center gap-2">
              <div className="flex w-8 items-center">
                <Image src={LogoImage} />
              </div>

              <span className="text-2xl font-bold capitalize text-indigo-900">
                portwind.
              </span>
            </div>
          </div>
        </nav>
        <div className="bg-blue-300">Whereas recognition</div>
      </div>
    </>
  )
}
